# Generated by Django 4.0.6 on 2022-07-28 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='social_login_id',
        ),
    ]
