# Generated by Django 4.0.6 on 2022-07-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_social_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_login_id',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
